In [ ]:
import pandas as pd
import numpy as np
from google.colab import files
import matplotlib.pyplot as plt

In [ ]:
uploaded=files.upload()

Saving iris.csv to iris.csv


In [ ]:
data=pd.read_csv("iris.csv");

In [ ]:
data.head()


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
data.shape


(150, 6)

In [ ]:
data.drop_duplicates()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [ ]:
data.isnull().sum()  #sum of missing values each column 

Id               0
SepalLengthCm    1
SepalWidthCm     1
PetalLengthCm    1
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
data=data.dropna()   #handling missing values 

In [ ]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  147.000000     147.000000    147.000000     147.000000    147.000000
mean    74.836735       5.834014      3.062585       3.722449      1.187075
std     43.636268       0.821000      0.432927       1.760479      0.766532
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     37.500000       5.100000      2.800000       1.550000      0.300000
50%     74.000000       5.800000      3.000000       4.300000      1.300000
75%    113.500000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
  
#Encode labels in column Species

data['Species']= label_encoder.fit_transform(data['Species'])
  
data['Species'].unique()

array([0, 1, 2])

In [ ]:
from sklearn.preprocessing import Normalizer

In [ ]:
import statistics as st

In [ ]:
m1=data.iloc[:,:-1]
m1.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [ ]:
n_max=Normalizer(norm="max")

In [ ]:
d=n_max.fit_transform(m1)

In [34]:
d

array([[0.19607843, 1.        , 0.68627451, 0.2745098 , 0.03921569],
       [0.40816327, 1.        , 0.6122449 , 0.28571429, 0.04081633],
       [0.63829787, 1.        , 0.68085106, 0.27659574, 0.04255319],
       [0.86956522, 1.        , 0.67391304, 0.32608696, 0.04347826],
       [1.        , 1.        , 0.72      , 0.28      , 0.04      ],
       [1.        , 0.9       , 0.65      , 0.28333333, 0.06666667],
       [1.        , 0.65714286, 0.48571429, 0.2       , 0.04285714],
       [1.        , 0.625     , 0.425     , 0.1875    , 0.025     ],
       [1.        , 0.48888889, 0.32222222, 0.15555556, 0.02222222],
       [1.        , 0.49      , 0.31      , 0.15      , 0.01      ],
       [1.        , 0.49090909, 0.33636364, 0.13636364, 0.01818182],
       [1.        , 0.4       , 0.28333333, 0.13333333, 0.01666667],
       [1.        , 0.36923077, 0.23076923, 0.10769231, 0.00769231],
       [1.        , 0.30714286, 0.21428571, 0.07857143, 0.00714286],
       [1.        , 0.38666667, 0.

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
ss=StandardScaler()

In [37]:
m1=data.iloc[:,:-1]

In [38]:
m1.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [39]:
scaled_data=ss.fit_transform(m1)

In [41]:
scaled_data

array([[-1.69788052, -0.89710507,  1.01381984, -1.32372422, -1.29211732],
       [-1.67488546, -1.14154334, -0.14505665, -1.32372422, -1.29211732],
       [-1.65189039, -1.38598161,  0.31849395, -1.38072114, -1.29211732],
       [-1.62889533, -1.50820074,  0.08671865, -1.26672731, -1.29211732],
       [-1.60590026, -1.0193242 ,  1.24559514, -1.32372422, -1.29211732],
       [-1.5829052 , -0.53044767,  1.94092104, -1.15273348, -1.03030995],
       [-1.55991013, -1.50820074,  0.78204454, -1.32372422, -1.16121364],
       [-1.53691507, -1.0193242 ,  0.78204454, -1.26672731, -1.29211732],
       [-1.51392   , -1.75263901, -0.37683195, -1.32372422, -1.29211732],
       [-1.49092494, -1.14154334,  0.08671865, -1.26672731, -1.423021  ],
       [-1.46792987, -0.53044767,  1.47737044, -1.26672731, -1.29211732],
       [-1.44493481, -1.26376247,  0.78204454, -1.2097304 , -1.29211732],
       [-1.42193974, -1.26376247, -0.14505665, -1.32372422, -1.423021  ],
       [-1.39894467, -1.87485814, -0.1

In [78]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, f_classif, SelectPercentile
from sklearn.decomposition import PCA



In [79]:
# Load the iris dataset
data = load_iris()

In [80]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, random_state=42)

In [81]:
# Convert target arrays to integer arrays
y_train = y_train.astype(int)
y_test = y_test.astype(int)

In [83]:
# Use SelectKBest to select the top 2 features
selector = SelectKBest(score_func=f_classif, k=2)
X_train_kbest = selector.fit_transform(X_train, y_train)
X_test_kbest = selector.transform(X_test)

In [84]:
# Use SelectPercentile to select the top 50% features
selector = SelectPercentile(percentile=50)
X_train_percentile = selector.fit_transform(X_train, y_train)
X_test_percentile = selector.transform(X_test)

In [86]:
# Print the selected features
selected_features = np.array(data.feature_names)[selector.get_support()]
print("SelectKBest selected the following features: ")
print(selected_features)

SelectKBest selected the following features: 
['petal length (cm)' 'petal width (cm)']


In [87]:
# Use SelectPercentile to select the top 50% features
selector = SelectPercentile(percentile=50)
X_train_percentile = selector.fit_transform(X_train, y_train)
X_test_percentile = selector.transform(X_test)

In [90]:
# Print the selected features
selected_features = np.array(data.feature_names)[selector.get_support()]
print("SelectPercentile selected the following features: ")
print(selected_features)

SelectPercentile selected the following features: 
['petal length (cm)' 'petal width (cm)']


In [91]:
# Use PCA to reduce the dimensionality to 2
pca = PCA(n_components=2)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

In [111]:
# Display results
print("Original Shape: ", data.data.shape)
print("SelectKBest")
print("SelectKBest train Shape: ", X_train_kbest.shape)
print("SelectKBest test Shape: ", X_test_kbest.shape)
print("SelectPercentile")
print("SelectPercentile train Shape: ", X_train_percentile.shape)
print("SelectPercentile test Shape:  ", X_test_percentile.shape)
print("PCA")
print("PCA train Shape: ", X_train_pca.shape)
print("PCA test Shape:  ",X_test_pca.shape)


Original Shape:  (150, 4)
SelectKBest
SelectKBest train Shape:  (112, 2)
SelectKBest test Shape:  (38, 2)
SelectPercentile
SelectPercentile train Shape:  (112, 2)
SelectPercentile test Shape:   (38, 2)
PCA
PCA train Shape:  (112, 2)
PCA test Shape:   (38, 2)
